### ISSUE TITLE
Missing demangling

### ISSUE THREAD

**Issue by copy** [mstange/profiler-get-symbols#30]
perf script has integrated demangling for OCaml (and Java, C++). It doesn't seem to be applied by fxprof-perf-convert (it works fine with the same perf.data when converting using `perf script` and opening in firefox profiler directly).

**Comment by mstange** [comment]
It looks like perf has four demanglers: C++, Rust, Java and OCaml: https://github.com/torvalds/linux/tree/e8a4e1c1bb697b1d9fc48f0e56dc0f50bc024bee/tools/perf/util (demangle-* files)

perf's OCaml demangler is here:

https://github.com/torvalds/linux/blob/e8a4e1c1bb697b1d9fc48f0e56dc0f50bc024bee/tools/perf/util/demangle-ocaml.c

We'd need a Rust implementation of that. Would you be willing to submit a patch to do that?

I've moved this issue into this repo because this is where we do the demangling: It's done during symbolication, which fxprof-perf-convert doesn't do itself, instead it happens with a network request to profiler-symbol-server, which makes use of profiler-get-symbols.

The code is here: https://github.com/mstange/profiler-get-symbols/blob/744797a529365585f4753ef53347a14a437de57c/lib/src/symbolicate/demangle.rs

**Comment by mstange** [comment]
And there are tests here: https://github.com/torvalds/linux/blob/fc661f2dcb7e41dcda9ae862efb822bb2f461646/tools/perf/tests/demangle-ocaml-test.c

**Comment by copy** [comment]
> We'd need a Rust implementation of that. Would you be willing to submit a patch to do that?

Yeah, I'll see what I can do.

**Comment by mstange** [comment]
I've published profiler-get-symbols v0.16.1.
If you re-run `cargo install profiler-symbol-server`, it should pick up that new version (because `cargo install` ignores `Cargo.lock`). Can you try it and see if the fix worked?

**Comment by copy** [comment]
> Can you try it and see if the fix worked?

Yes, I can confirm that it works.

**Comment by mstange** [comment]
Great!
